// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaOTlWQ-gKupPnKCjxIi-WDGXZjN5tmyk',
    appId: '1:1057988596602:web:3aa38d46db5ba37c5e3cc3',
    messagingSenderId: '1057988596602',
    projectId: 'mynotes-ruhulaminjr',
    authDomain: 'mynotes-ruhulaminjr.firebaseapp.com',
    storageBucket: 'mynotes-ruhulaminjr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWkRcB24xnJuMnsVXUax-PG-h_j66zSI',
    appId: '1:1057988596602:android:70a6c1ec6f3670d85e3cc3',
    messagingSenderId: '1057988596602',
    projectId: 'mynotes-ruhulaminjr',
    storageBucket: 'mynotes-ruhulaminjr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDDflLjjHRo-mC6ssBqFvbfmKAXu11x0',
    appId: '1:1057988596602:ios:02d261d16a8211bf5e3cc3',
    messagingSenderId: '1057988596602',
    projectId: 'mynotes-ruhulaminjr',
    storageBucket: 'mynotes-ruhulaminjr.appspot.com',
    iosClientId: '1057988596602-3u6m87diitpsmskk3b0c8sp9rlp6nimn.apps.googleusercontent.com',
    iosBundleId: 'com.ruhulaminjr.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeDDflLjjHRo-mC6ssBqFvbfmKAXu11x0',
    appId: '1:1057988596602:ios:3ad9c4665d32752d5e3cc3',
    messagingSenderId: '1057988596602',
    projectId: 'mynotes-ruhulaminjr',
    storageBucket: 'mynotes-ruhulaminjr.appspot.com',
    iosClientId: '1057988596602-m59hbu97tc7re9f5dhhcg2n5bgtspp9f.apps.googleusercontent.com',
    iosBundleId: 'com.ruhulaminjr.mynotes.RunnerTests',
  );
}
